version: '3'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:8000"
    volumes:
      - .:/usr/src/app/
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://db:27017/mern-starter
    command: npm run bs

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
     - data:/database

volumes:
  data:
    driver: local
