version: '3'
services:
  web:
    image: rykeller/mern
    links:
     - db
    ports:
     - "80:8000"
    volumes:
     - .:/usr/src/app/
    environment:
     NODE_ENV: production
     MONGO_URL: mongodb://localhost:27017/mern-starter
  db:
    image: mongo:latest
    ports:
     - "27017:27017"
